name: CI/CD
on: push
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      CI: true
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Install
        run: yarn install
      - name: Integrate
        run: yarn integrate
